first_name = input("what is your name? ")
print(f"Hello {first_name}")
mood = input("How are you today? ")
print(f"I am also doing {mood}")
reply1 = input("is matthew the best? ")
print(f"good choice")
reply2 = input("is matthew very very cute? (the only answer is yes) " )
print(f"i agree, matthew is obviously the cutest person on earth")
reply3 = input("should matthew become president of the USA? (pick yes)")
print(f"matthew would make a very good president")